name,pos,dollar
Patrick Mahomes,qb,59
Ben Roethlisberger,qb,40
Aaron Rodgers,qb,55
Russell Wilson,qb,34
Matt Ryan,qb,30
Jared Goff,qb,26
Andrew Luck,qb,32
Jameis Winston,qb,16
Deshaun Watson,qb,32
Tom Brady,qb,50
Philip Rivers,qb,55
Lamar Jackson,qb,37
Nick Foles,qb,34
Josh Allen,qb,14
Mitchell Trubisky,qb,22
Saquon Barkley,rb,55
Melvin Gordon,rb,49
Joe Mixon,rb,36
Jamaal Williams,rb,31
Chris Carson,rb,26
James Conner,rb,25
Christian McCaffrey,rb,44
C.J. Anderson,rb,31
Nick Chubb,rb,29
David Johnson,rb,37
Derrick Henry,rb,24
Dalvin Cook,rb,18
Elijah McGuire,rb,16
Sony Michel,rb,26
Tarik Cohen,rb,34
Julio Jones,wr,62
DeAndre Hopkins,wr,61
Tyreek Hill,wr,60
JuJu Smith-Schuster,wr,56
Keenan Allen,wr,55
Mike Evans,wr,50
Antonio Brown,wr,46
T.Y. Hilton,wr,44
Robert Woods,wr,34
Adam Thielen,wr,39
Julian Edelman,wr,40
Brandin Cooks,wr,36
Stefon Diggs,wr,34
Alshon Jeffery,wr,26
Jarvis Landry,wr,36
Robby Anderson,wr,18
Doug Baldwin,wr,22
Tyler Lockett,wr,18
Adam Humphries,wr,26
Corey Davis,wr,14
Sterling Shepard,wr,30
Larry Fitzgerald,wr,11
Amari Cooper,wr,30
DaeSean Hamilton,wr,12
Calvin Ridley,wr,20
Mohamed Sanu,wr,10
DJ Moore,wr,8
Michael Thomas,wr,50
Chris Godwin,wr,14
Josh Reynolds,wr,4
Robert Foster,wr,4
Courtland Sutton,wr,3
Jordy Nelson,wr,3
Randall Cobb,wr,1
Dede Westbrook,wr,1
Marquez Valdes-Scantling,wr,1
Jamison Crowder,wr,1
Mike Williams,wr,6
Curtis Samuel,wr,2
John Ross,wr,1
Tim Patrick,wr,1
Taylor Gabriel,wr,1
Chris Conley,wr,0
Golden Tate,wr,1
Zay Jones,wr,1
Travis Kelce,te,39
Zach Ertz,te,37
George Kittle,te,30
Eric Ebron,te,29
Jared Cook,te,18
Rob Gronkowski,te,19
Austin Hooper,te,6
Evan Engram,te,8
Kyle Rudolph,te,12
Jimmy Graham,te,4
Seattle Seahawks,dst,12
Houston Texans,dst,8
Chicago Bears,dst,7
Buffalo Bills,dst,7
Philadelphia Eagles,dst,2
Los Angeles Rams,dst,4
Baltimore Ravens,dst,9
New Orleans Saints,dst,2
Pittsburgh Steelers,dst,3
New England Patriots,dst,4
Minnesota Vikings,dst,1
Los Angeles Chargers,dst,1
Kansas City Chiefs,dst,2
Indianapolis Colts,dst,3
Miami Dolphins,dst,1